### ISSUE TITLE
package will be deprecated

### ISSUE THREAD

**Issue by 111111-s** [figment-networks/tutorials#14]
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.

**Comment by FATiST** [comment]
same problem.

**Comment by Piratnewtime** [comment]
same problem.

**Comment by Rakhymzhan** [comment]
same problem.

**Comment by yash-sharma1** [comment]
Hey folks,
It's related to the packages you're installing so make sure to install the latest updated packages.
