### ISSUE TITLE
NEAR contract compilation problem

### ISSUE THREAD

**Issue by dzarezenko** [figment-networks/tutorials#5]
When I am trying to compile a smart contract from the NEAR example I received the next error:

![image](https://user-images.githubusercontent.com/148570/101501723-c4782900-3978-11eb-8852-2a7a29a8da87.png)

What could be the problem?

**Comment by lavabyrd** [comment]
Hey @dzarezenko , 

Thanks for reaching out. We actually provide support directly at Discord which you can access [here](https://discord.com/invite/fszyM7K).

I'll close this ticket for now but if you pop over there, we'll be able to help you out.

Many Thanks!
Mark

**Comment by willemneal** [comment]
Sorry a pre-release somehow was picked up by npm as the real release.  I pushed a patch that should fix this.
